### ISSUE TITLE
Not enough people know about the GitHub issue tracker.

### ISSUE THREAD

**Issue by uakotaobi** [eshsrobotics/vex#1]
This is my issue description.

**Comment by Natan92** [comment]
This is true

**Comment by Xmassub** [comment]
Wowe

**Comment by vickensemerdjian** [comment]
i know though! also *fancy* becuase im **cool**

_edit_: __*more fancy!*__

**Comment by Slickshot11** [comment]
Tis an issue!

**Comment by Xmassub** [comment]
> i know though! also _fancy_ becuase im **cool**

Imagine using thumbs up on your own post

**Comment by wildstorm43** [comment]
i am writing something smart and knowledgeable

**Comment by vickensemerdjian** [comment]
> 
> 
> > i know though! also _fancy_ becuase im **cool**
> 
> Imagine using thumbs up on your own post

# im not guilty!

**Comment by Ryan429** [comment]
What a tragedy

**Comment by uakotaobi** [comment]
Well done, folks.
